/* parser generated by jison 0.4.13 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var pil = (function(){
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"program":3,"statements":4,"EOF":5,"statement":6,"booster-statement":7,"booster-thrust-statement":8,"booster-stop-statement":9,"thrust":10,"booster-identifier":11,"booster-power":12,"for-statement":13,"until-statement":14,"booster-position":15,".":16,"booster-orientation":17,"fore":18,"aft":19,"port":20,"starboard":21,"horizontal":22,"vertical":23,"NUMBER":24,"variable":25,"stop":26,"for":27,"time-period":28,"until":29,"condition":30,"is":31,"rvalue":32,"not":33,"greater":34,"than":35,"less":36,"literal":37,"true":38,"false":39,"STRING":40,"seconds":41,"milliseconds":42,"minutes":43,"frames":44,"pitch":45,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",10:"thrust",16:".",18:"fore",19:"aft",20:"port",21:"starboard",22:"horizontal",23:"vertical",24:"NUMBER",26:"stop",27:"for",29:"until",31:"is",33:"not",34:"greater",35:"than",36:"less",38:"true",39:"false",40:"STRING",41:"seconds",42:"milliseconds",43:"minutes",44:"frames",45:"pitch"},
productions_: [0,[3,2],[4,1],[4,2],[6,1],[7,1],[7,1],[8,4],[8,4],[8,3],[11,3],[15,1],[15,1],[15,1],[15,1],[17,1],[17,1],[12,1],[12,1],[9,2],[13,2],[14,2],[30,1],[30,3],[30,4],[30,4],[30,4],[32,1],[32,1],[37,1],[37,1],[37,1],[37,1],[28,2],[28,2],[28,2],[28,2],[25,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:return $$[$0-1];
break;
case 2:this.$ = $$[$0];
break;
case 3:this.$ = $$[$0];
break;
case 4:this.$ = $$[$0];
break;
case 5:this.$ = $$[$0];
break;
case 6:this.$ = $$[$0];
break;
case 7:
            game.ship.boostersByName[$$[$0-2]].power = $$[$0-1];
            setTimeout(function() {
                game.ship.boostersByName[$$[$0-2]].power = 0;
            },$$[$0]);
            this.$ = $$[$0-1];
        
break;
case 8:
            game.ship.boostersByName[$$[$0-2]].power = $$[$0-1];
            game.addFunction(function() {
                if($$[$0]) {
                    game.ship.boostersByName[$$[$0-2]].power = 0;
                    return true;
                } else {
                    return false;
                }
            });

            this.$ = $$[$0-1];
        
break;
case 9:
            game.ship.boostersByName[$$[$0-1]].power = $$[$0];
            this.$ = $$[$0];
        
break;
case 10:this.$ = $$[$0-2] + " " + $$[$0]
break;
case 11:this.$ = "fore";
break;
case 12:this.$ = "aft";
break;
case 13:this.$ = "port";
break;
case 14:this.$ = "starboard";
break;
case 15:this.$ = "horizontal";
break;
case 16:this.$ = "vertical";
break;
case 17:
            if($$[$0] < 0 || $$[$0] > 100) {
                throw new Error('Booster power out of range.  Should be 0 to 100.');
            }
            this.$ = $$[$0];
        
break;
case 19:
            game.ship.boostersByName[$$[$0]].power = 0;
            this.$ = $$[$0];
        
break;
case 20:this.$ = $$[$0];
break;
case 21:$$[$0]
break;
case 22:this.$ = $$[$0];
break;
case 23:this.$ = ($$[$0-2] == $$[$0]);
break;
case 24:this.$ = ($$[$0-3] != $$[$0-1]);
break;
case 25:this.$ = ($$[$0-3] > $$[$0-1]);
break;
case 26:this.$ = ($$[$0-3] < $$[$0-1]);
break;
case 33:this.$ = $$[$0-1] * 1000;
break;
case 34:this.$ = $$[$0-1];
break;
case 35:this.$ = $$[$0-1] * 60000;
break;
case 36:this.$ = $$[$0-1] / 30;
break;
case 37:this.$ = game.ship.location.rotation.x;
break;
}
},
table: [{3:1,4:2,6:3,7:4,8:5,9:6,10:[1,7],26:[1,8]},{1:[3]},{5:[1,9],6:10,7:4,8:5,9:6,10:[1,7],26:[1,8]},{5:[2,2],10:[2,2],26:[2,2]},{5:[2,4],10:[2,4],26:[2,4]},{5:[2,5],10:[2,5],26:[2,5]},{5:[2,6],10:[2,6],26:[2,6]},{11:11,15:12,18:[1,13],19:[1,14],20:[1,15],21:[1,16]},{11:17,15:12,18:[1,13],19:[1,14],20:[1,15],21:[1,16]},{1:[2,1]},{5:[2,3],10:[2,3],26:[2,3]},{12:18,24:[1,19],25:20,45:[1,21]},{16:[1,22]},{16:[2,11]},{16:[2,12]},{16:[2,13]},{16:[2,14]},{5:[2,19],10:[2,19],26:[2,19]},{5:[2,9],10:[2,9],13:23,14:24,26:[2,9],27:[1,25],29:[1,26]},{5:[2,17],10:[2,17],26:[2,17],27:[2,17],29:[2,17]},{5:[2,18],10:[2,18],26:[2,18],27:[2,18],29:[2,18]},{5:[2,37],10:[2,37],26:[2,37],27:[2,37],29:[2,37],31:[2,37],34:[2,37],36:[2,37]},{17:27,22:[1,28],23:[1,29]},{5:[2,7],10:[2,7],26:[2,7]},{5:[2,8],10:[2,8],26:[2,8]},{24:[1,31],28:30},{25:33,30:32,45:[1,21]},{5:[2,10],10:[2,10],24:[2,10],26:[2,10],45:[2,10]},{5:[2,15],10:[2,15],24:[2,15],26:[2,15],45:[2,15]},{5:[2,16],10:[2,16],24:[2,16],26:[2,16],45:[2,16]},{5:[2,20],10:[2,20],26:[2,20]},{41:[1,34],42:[1,35],43:[1,36],44:[1,37]},{5:[2,21],10:[2,21],26:[2,21]},{5:[2,22],10:[2,22],26:[2,22],31:[1,38],34:[1,39],36:[1,40]},{5:[2,33],10:[2,33],26:[2,33]},{5:[2,34],10:[2,34],26:[2,34]},{5:[2,35],10:[2,35],26:[2,35]},{5:[2,36],10:[2,36],26:[2,36]},{24:[1,45],25:43,32:41,33:[1,42],37:44,38:[1,46],39:[1,47],40:[1,48],45:[1,21]},{35:[1,49]},{35:[1,50]},{5:[2,23],10:[2,23],26:[2,23]},{24:[1,45],25:43,32:51,37:44,38:[1,46],39:[1,47],40:[1,48],45:[1,21]},{5:[2,27],10:[2,27],26:[2,27]},{5:[2,28],10:[2,28],26:[2,28]},{5:[2,29],10:[2,29],26:[2,29]},{5:[2,30],10:[2,30],26:[2,30]},{5:[2,31],10:[2,31],26:[2,31]},{5:[2,32],10:[2,32],26:[2,32]},{24:[1,45],25:43,32:52,37:44,38:[1,46],39:[1,47],40:[1,48],45:[1,21]},{24:[1,45],25:43,32:53,37:44,38:[1,46],39:[1,47],40:[1,48],45:[1,21]},{5:[2,24],10:[2,24],26:[2,24]},{5:[2,25],10:[2,25],26:[2,25]},{5:[2,26],10:[2,26],26:[2,26]}],
defaultActions: {9:[2,1],13:[2,11],14:[2,12],15:[2,13],16:[2,14]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        throw new Error(str);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    this.lexer.setInput(input);
    this.lexer.yy = this.yy;
    this.yy.lexer = this.lexer;
    this.yy.parser = this;
    if (typeof this.lexer.yylloc == 'undefined') {
        this.lexer.yylloc = {};
    }
    var yyloc = this.lexer.yylloc;
    lstack.push(yyloc);
    var ranges = this.lexer.options && this.lexer.options.ranges;
    if (typeof this.yy.parseError === 'function') {
        this.parseError = this.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    function lex() {
        var token;
        token = self.lexer.lex() || EOF;
        if (typeof token !== 'number') {
            token = self.symbols_[token] || token;
        }
        return token;
    }
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (this.lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + this.lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: this.lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: this.lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(this.lexer.yytext);
            lstack.push(this.lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = this.lexer.yyleng;
                yytext = this.lexer.yytext;
                yylineno = this.lexer.yylineno;
                yyloc = this.lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                this.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};
/* generated by jison-lex 0.2.1 */
var lexer = (function(){
var lexer = {

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input) {
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len - 1);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function (match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex() {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState(condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {

var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* Skip whitespace */
break;
case 1:return '*';
break;
case 2:return '/';
break;
case 3:return '-';
break;
case 4:return '+';
break;
case 5:return '^';
break;
case 6:return '(';
break;
case 7:return ')';
break;
case 8:return 'PI';
break;
case 9:return 'E';
break;
case 10:return ';';
break;
case 11:return 10;
break;
case 12:return 26;
break;
case 13:return 27;
break;
case 14:return 29;
break;
case 15:return 18;
break;
case 16:return 19;
break;
case 17:return 20;
break;
case 18:return 21;
break;
case 19:return 20;
break;
case 20:return 21;
break;
case 21:return 18;
break;
case 22:return 'back';
break;
case 23:return 22;
break;
case 24:return 23;
break;
case 25:return 41;
break;
case 26:return 41;
break;
case 27:return 41;
break;
case 28:return 43;
break;
case 29:return 43;
break;
case 30:return 42;
break;
case 31:return 42;
break;
case 32:return 44;
break;
case 33:return 24;
break;
case 34:return 5;
break;
case 35:return 40;
break;
case 36:return 31;
break;
case 37:return 31;
break;
case 38:return 31;
break;
case 39:return 'is not';
break;
case 40:return 'is not';
break;
case 41:return 'greater than';
break;
case 42:return 'greater than';
break;
case 43:return 'greater than';
break;
case 44:return 'less than';
break;
case 45:return 'less than';
break;
case 46:return 'less than';
break;
case 47:return 45;
break;
case 48:return 16;
break;
case 49:console.log("invalid token: " + yy_.yytext); return 'INVALID';
break;
}
},
rules: [/^(?:\s+)/,/^(?:\*)/,/^(?:\/)/,/^(?:-)/,/^(?:\+)/,/^(?:\^)/,/^(?:\()/,/^(?:\))/,/^(?:PI\b)/,/^(?:E\b)/,/^(?:;)/,/^(?:thrust\b)/,/^(?:stop\b)/,/^(?:for\b)/,/^(?:until\b)/,/^(?:fore\b)/,/^(?:aft\b)/,/^(?:port\b)/,/^(?:starboard\b)/,/^(?:left\b)/,/^(?:right\b)/,/^(?:front\b)/,/^(?:back\b)/,/^(?:horizontal\b)/,/^(?:vertical\b)/,/^(?:seconds\b)/,/^(?:second\b)/,/^(?:s\b)/,/^(?:minutes\b)/,/^(?:minute\b)/,/^(?:milliseconds\b)/,/^(?:ms\b)/,/^(?:frames\b)/,/^(?:[0-9]+(\.[0-9]+)?\b)/,/^(?:$)/,/^(?:".*")/,/^(?:is\b)/,/^(?:=)/,/^(?:==)/,/^(?:is not\b)/,/^(?:!=)/,/^(?:greater than\b)/,/^(?:is greater than\b)/,/^(?:>)/,/^(?:less than\b)/,/^(?:is less than\b)/,/^(?:<)/,/^(?:pitch\b)/,/^(?:\.)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49],"inclusive":true}}
};
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = pil;
exports.Parser = pil.Parser;
exports.parse = function () { return pil.parse.apply(pil, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}